name: Alarm Clock
title: Alarm Clock
email: your-email@example.com
description: Simple to use online alarm clock to wake up after specific time or at specific times
baseurl: '' # the subpath of your site, e.g. /blog
url: https://alarmsetter.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
favicon: assets/images/logo.png
paginate: '12'
paginate_path: '/blog/page:num/'
theme: best-blogging-theme

disqus:
  shortname: disquesName

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
